# -*- coding: utf-8 -*-
"""Field-selected extract of `ops/DIRECTORY_CREATION_GRANTS.md`.

WHY AN EXTRACT AND NOT THE DOCUMENT. Aaron's bounded admission (2026-09-10)
authorized READ-ONLY access to the grant record, and the whole document went
into the first cut. A claim-blind scan added on 2026-09-11 found that its
correction sections carry a MEASURED TEST RESULT about the implementation
under review -- a builder's statement that a gate passes in three cases.
That is the category the N14-EXACT-TREE-004 stop was about: an authority
artifact carrying prior judgments of the implementation.

WHAT EXECUTION ACTUALLY NEEDS is one marker. `tests/_governed_subtrees.py`
reads the record and asserts a single string is present; nothing else in it
is parsed. So the extract keeps the AUTHORIZATION material -- the five slots
a grant must have, the falsifier, the ledger and its execution record -- and
drops every retrospective correction section. Least privilege: this is
strictly narrower than the admission granted, not wider.

THE CUT IS STRUCTURAL, not a line number: everything from the first
retrospective H2 heading onward. If the document grows another correction
section, it is excluded automatically rather than silently admitted.

THE EXCLUSIONS ARE COUNTED, NEVER RESTATED. That is the same rule
`build_rules_extract_lib.py` follows, and for the same reason: telling the
reviewer that three sections were withheld is transport honesty; telling
them what those sections concluded is the leak itself.
"""
import re
from pathlib import Path

SOURCE = "ops/DIRECTORY_CREATION_GRANTS.md"

#: The first retrospective heading ends the normative part. Both spellings
#: the document actually uses are matched; a new one that matches neither
#: would be KEPT, so the claim-blind scan is the backstop and this is the
#: primary. Two independent mechanisms, on purpose.
RETRO_HEADING = re.compile(
    r"^##\s+(订正|第\s*2\s*行的证据事故)")

#: What `tests/_governed_subtrees.py` requires to be present.
REQUIRED_MARKER = "**USED（用掉即失效）**"

BANNER = """<!-- FIELD-SELECTED EXTRACT -- NOT THE REPOSITORY DOCUMENT.

Generated by scripts/build_grant_extract_lib.py from {source} at the
reviewed commit. It carries the AUTHORIZATION material only: the slots a
grant must have, the falsifier, the ledger and its execution record.

{n} later section(s) of the source document are EXCLUDED and deliberately
not summarised here. They are retrospective corrections that state prior
measured results about the implementation this review is judging, and
handing you those would break the blindness this bundle exists to keep.
Their exclusion is recorded so that you know the document is partial --
which is a fact you are entitled to -- without learning their content.

If you judge that this obligation cannot be answered without the excluded
material, that is a DELIVERY_FAILURE and the correct response is to say so
and stop, not to reason around the gap.
-->

"""


def render(repo: Path) -> bytes:
    src = repo / SOURCE
    lines = src.read_text(encoding="utf-8").splitlines(keepends=True)
    cuts = [i for i, ln in enumerate(lines) if RETRO_HEADING.match(ln)]
    if not cuts:
        raise SystemExit(
            "GRANT extract refused: no retrospective heading found in %s. "
            "Either the document changed shape or the pattern is stale; "
            "shipping the whole document on that assumption is exactly the "
            "leak this extract exists to close." % SOURCE)
    cut = cuts[0]
    kept = "".join(lines[:cut])
    excluded = sum(1 for ln in lines[cut:] if ln.startswith("## "))
    if REQUIRED_MARKER not in kept:
        raise SystemExit(
            "GRANT extract refused: the kept part lost the marker "
            "tests/_governed_subtrees.py asserts. An extract that does not "
            "satisfy execution is a broken bundle, not a safer one.")
    text = BANNER.format(source=SOURCE, n=excluded) + kept
    return text.replace("\r\n", "\n").encode("utf-8")
