# -*- coding: utf-8 -*-
"""VERIFY.md -- the contract for a POST-HOLD REMEDIATION VERIFICATION.

WHY THIS IS A DIFFERENT DOCUMENT FROM `REVIEW.md`. That one opens an
outcome-blind, judgment-first adjudication of O1-O13 against a tree the
reviewer has never seen. This one opens something much narrower and with the
opposite blindness posture on exactly one axis: the reviewer's OWN frozen
findings are the comparand, deliberately, because closure cannot be verified
against a baseline the verifier is not allowed to read.

Everything else is unchanged. Outcome blindness stands. The delivery is sealed,
the guard arms before pytest, the workspace is supplied explicitly, and a
builder sentence is worth nothing here that it was not worth before.
"""


def _targets_section(profile: dict, add) -> None:
    for target in profile["verification_targets"]:
        add("### %s -- %s" % (target["id"], target["title"]))
        add("")
        add("**FROZEN FINDING (the claim under verification).** %s"
            % target["frozen_finding"])
        add("")
        add("**WHERE TO LOOK.** The repaired loci are:")
        add("")
        for locus in target["loci"]:
            add("* `%s`" % locus)
        add("")
        add("**WHAT CLOSURE REQUIRES.** %s" % target["closure_requires"])
        add("")
        if target.get("frozen_probe_refs"):
            add("**THE PROBE THAT ESTABLISHED IT.** %s"
                % ", ".join("`%s`" % r for r in target["frozen_probe_refs"]))
            add("")
        add("**BUILDER'S CLAIM, which is SELF_REPORTED and proves nothing.** %s"
            % target["builder_claim"])
        add("")


def render(profile: dict) -> str:
    L = []
    a = L.append
    frozen = profile["frozen_baseline"]
    target = profile["repaired_target"]

    a("# VERIFY -- %s" % profile["review_id"])
    a("")
    a("```")
    a("VERIFICATION_ID    = %s" % profile["review_id"])
    a("KIND               = POST-HOLD REMEDIATION VERIFICATION")
    a("THIS IS NOT        = N14 Round 3. It is not a substantive round of any")
    a("                     kind, it consumes no review round, and it does not")
    a("                     reopen O1-O13.")
    a("ROUND ACCOUNTING   = unchanged. Round 1 HOLD/CONSUMED, Round 2")
    a("                     HOLD/CONSUMED, ordinary N14 budget EXHAUSTED.")
    a("CONTRACT           = %s" % profile["contract_version"])
    a("PROFILE            = %s" % profile["profile_version"])
    a("BLINDNESS          = OUTCOME_BLIND. Judgment-first does NOT apply to the")
    a("                     frozen F01-F07 comparand: those findings are the")
    a("                     verification baseline on purpose, and closure")
    a("                     cannot be checked against a baseline you may not")
    a("                     read. Everything else is unchanged.")
    a("SEAT               = the SAME independent session that authored the")
    a("                     frozen Round-2 findings. That is deliberate here")
    a("                     and is the one place this differs from an ordinary")
    a("                     review seat: you are checking whether YOUR OWN")
    a("                     stated failure paths still exist.")
    a("MUST_NOT_BE        = the builder (Claude Opus / Claude Code) session or")
    a("                     any subagent of it.")
    a("REAL_MC_AUTHORIZED = NO    REAL_MC_EXECUTED = NO")
    a("STATISTICAL_SIGNAL = NOT_TESTED    STATISTICAL_OUTCOME_EXPOSED = NO")
    a("```")
    a("")

    a("## 0. What you are being asked, and what you are not")
    a("")
    a("**ASKED:** for each of the seven frozen findings F01-F07, determine")
    a("independently whether the stated failure path still exists in the exact")
    a("repaired tree carried in `tree/`.")
    a("")
    a("**NOT ASKED:** to re-adjudicate O1-O13, to audit the repository, to")
    a("re-derive the Round-2 verdict, or to look for new findings outside the")
    a("seven. If you see something outside scope that you judge serious, say so")
    a("in a clearly separated section -- do not fold it into a closure verdict.")
    a("")
    a("**A BUILDER SENTENCE IS NOT EVIDENCE HERE EITHER.** Every 'FIX' and")
    a("'BUILDER'S CLAIM' line below is SELF_REPORTED. The repaired source, the")
    a("focused tests and your own frozen probes are in this package precisely")
    a("so that closure can be established rather than accepted.")
    a("")

    a("## 1. The exact repaired target")
    a("")
    a("```")
    a("REPAIR_COMMIT   = %s" % target["repair_commit"])
    a("ROOT_TREE       = %s" % target["root_tree"])
    a("ITSF_SRC_TREE   = %s" % target["itsf_src_tree"])
    a("MC_SUBTREE_TREE = %s" % target["mc_subtree_tree"])
    a("```")
    a("")
    a("`tree/` is a Git export of that commit, file by file, and `MANIFEST.json`")
    a("records each file's blob id beside its sha256. Verify `MANIFEST.json`")
    a("against the digest you were given out of band, then check every payload")
    a("row against the file it names. `MANIFEST.json` does not contain its own")
    a("hash -- a document that certifies itself certifies nothing.")
    a("")
    a("**The six production files the repair touched:**")
    a("")
    for path in profile["repaired_target"]["production_files_changed"]:
        a("* `%s`" % path)
    a("")
    a("Nothing else in `src/` moved. That claim is checkable here: the three")
    a("tree digests above pin it, and `git` is not needed to check them because")
    a("every payload row carries its blob id.")
    a("")

    a("## 2. The frozen baseline, carried byte-exact")
    a("")
    a("`frozen/` holds YOUR Round-2 returns and probes, unmodified:")
    a("")
    a("```")
    for row in frozen["artifacts"]:
        a("%-32s %8d bytes  %s" % (row["name"], row["byte_count"],
                                   row["sha256"][:16] + "..."))
    a("```")
    a("")
    a("`frozen/FREEZE.json` declares `INITIAL_FINDINGS_SHA256 = %s`."
      % frozen["initial_findings_sha256"])
    a("The carried `frozen/INITIAL_FINDINGS.md` hashes to exactly that, so the")
    a("baseline you are verifying against is provably the one you froze. Check")
    a("it yourself; it is one hash.")
    a("")
    a("**Nothing in `frozen/` was edited, reformatted or excerpted.** If any of")
    a("it disagrees with how a finding is restated in section 3, `frozen/` is")
    a("authoritative and the restatement is the defect.")
    a("")
    a("**One honest note about the blindness machinery.** An ordinary delivery")
    a("runs a CLAIM_BLIND scan that refuses any admitted prose carrying prior")
    a("judgement of the implementation under review. This package carries")
    a("exactly that, on purpose -- and the scan did not fire on any of it. The")
    a("patterns are narrow and do not match your phrasing, so no exemption was")
    a("needed and none is declared. Read that as: the gate is not what is")
    a("keeping this package honest here; the declared purpose is. The outcome")
    a("scan is unchanged and did run over every byte.")
    a("")

    a("## 3. The seven verification targets")
    a("")
    a("Each is stated as the FROZEN claim, the repaired loci, and what closure")
    a("requires. The closure criterion is the finding's own required repair")
    a("intent -- not a criterion invented to be satisfiable.")
    a("")
    _targets_section(profile, a)

    a("## 4. The two targets Aaron singled out")
    a("")
    a("### A. F02 and the ruled doubling bound")
    a("")
    a("The repair asserts that the frozen authority makes K -> 2K expressible")
    a("for every governed seed but does NOT authorize an invented 4K/8K")
    a("escalation, and that it therefore applied the bound rather than")
    a("extending it. **Do not accept that reading.** Compare the repaired")
    a("behaviour against the authority directly:")
    a("")
    a("* `authority/RULES_EXTRACT.md` and `tree/MC_METHOD_SPEC.md` carry the")
    a("  governing rules, including (e) and `GridRepeatPolicy.max_doublings`;")
    a("* `tree/src/itsf/contracts.py` carries the ruled policy values;")
    a("* `tree/src/itsf/mc/grid_replay.py` carries the frozen-k guard")
    a("  (`grid_replay_k_per_seed_not_frozen`) and the 2x guard")
    a("  (`grid_replay_k_doubling_violation`) that the builder says make a")
    a("  second doubling inexpressible;")
    a("* the aggregate records `doublings_executed` and `max_doublings`.")
    a("")
    a("**The question to answer is not whether the builder's story is coherent.**")
    a("It is whether the required bounded doubling/escalation semantics are")
    a("FULLY satisfied by what the repaired code does. If they are not, say so")
    a("and name the exact rule that is unmet.")
    a("")
    a("### B. F06 and the governed Owner release")
    a("")
    a("The generic writer must refuse `OWNER_RELEASE`. The legitimate")
    a("Owner-action path now reaches the one physical write through the")
    a("compare-and-swap directly, rather than through the generic entry.")
    a("Establish that this preserves ALL of:")
    a("")
    a("* the actor/Owner boundary (the row's actor cell, and who may file it);")
    a("* hold identity -- a release names the hold it releases and only that;")
    a("* the compare-and-swap condition against the decided snapshot;")
    a("* serialization and integrity -- one lock, one write, tail-newline and")
    a("  post-write re-parse;")
    a("* downstream hold-state semantics -- what `active_holds` and")
    a("  `holds_applicable_to_start` answer before and after.")
    a("")
    a("The loci are `tree/src/itsf/mc/registry_boundary.py` (`serialized_append`,")
    a("`_compare_and_append`, `_append_owner_row`, `append_owner_release`,")
    a("`_physical_serialized_write`) and `tree/src/itsf/mc/owner_control.py`.")
    a("**A bypass here would be worse than the finding it repairs**, so this is")
    a("the one place where 'the tests pass' is explicitly not enough.")
    a("")

    a("## 5. Running the focused evidence")
    a("")
    a("```")
    a("run_review.cmd --review-output-base \"<the writable base your dispatch names>\"")
    a("```")
    a("")
    a("Same launcher, same sealed runtime, same explicit workspace capability as")
    a("the delivery you last ran -- nothing about that machinery changed. It")
    a("takes exactly one argument: the writable base your dispatch authorised.")
    a("There is no default and `TMP`/`TEMP`/`TMPDIR` are never read to choose")
    a("one.")
    a("")
    a("It runs the selected repository tests from `tree/` plus the boundary")
    a("probes. `%s` is the focused F01-F07 evidence"
      % profile["focused_test_file"])
    a("and is the file to read first: every test in it asserts a FINAL")
    a("OBSERVABLE -- the seal candidate, the returned object, the ledger bytes --")
    a("rather than that a helper exists or a source string appears. That")
    a("distinction is the builder's own account of why several of your findings")
    a("survived a green suite; judge whether the new tests actually avoid it.")
    a("")
    a("**Guard denials.** `GUARD_REPORT.json` splits `expected_denials` from")
    a("`unexpected_denials`: a sealed negative control declares the refusal it")
    a("is about to cause. STOP on a non-empty `unexpected_denials`, on a")
    a("non-empty `missing_prescribed_denials`, or on any launcher/runtime")
    a("refusal. The runner applies the same rule and exits non-zero on it,")
    a("independently of the test result.")
    a("")
    a("**Builder-reported figures, SELF_REPORTED, for you to confirm or refute:**")
    a("")
    a("```")
    for line in profile["builder_reported_measurements"]:
        a(line)
    a("```")
    a("")
    a("The affected-suite figures above were measured OUTSIDE this sealed")
    a("package -- those suites use `subprocess`, `git` and source introspection,")
    a("which the execution guard denies by design, so they cannot run in here.")
    a("They are stated as builder self-reports and are not offered as evidence.")
    a("Their SOURCE is not in this package either; if you need it to judge a")
    a("closure, that is a transport defect worth reporting.")
    a("")

    a("## 6. Your output")
    a("")
    a("Write into the review workspace the launcher prints, never into this")
    a("delivery, which is immutable:")
    a("")
    a("```")
    a("<review workspace>\\VERIFICATION_FINDINGS.md")
    a("<review workspace>\\VERIFICATION_FREEZE.json")
    a("<review workspace>\\VERIFICATION_ATTESTATION.md")
    a("```")
    a("")
    a("`VERIFICATION_FINDINGS.md` must give, for EACH of F01-F07:")
    a("")
    a("```")
    a("CLOSURE          CLOSED | NOT_CLOSED | CLOSED_WITH_RESERVATION")
    a("BASIS            what you executed or read that established it")
    a("EXAMINED_LOCUS   the exact file and symbol")
    a("EVIDENCE_CLASS   REPRODUCED | READ | SELF_REPORTED")
    a("RESIDUAL         what closure does NOT cover, if anything")
    a("```")
    a("")
    a("`CLOSED_WITH_RESERVATION` exists so that a repair which closes the stated")
    a("failure path while leaving a named narrower one open can be recorded")
    a("honestly instead of being forced into a binary.")
    a("")
    a("End with:")
    a("")
    a("```")
    a("REMEDIATION_VERIFIED        every finding CLOSED")
    a("REMEDIATION_PARTIAL         at least one CLOSED_WITH_RESERVATION, none NOT_CLOSED")
    a("REMEDIATION_NOT_VERIFIED    at least one NOT_CLOSED")
    a("```")
    a("")
    a("There is no fourth value and this is **not** a GO/STOP verdict on N14.")
    a("Whether N14 proceeds is Aaron's decision and is not being delegated here.")
    a("")
    a("Then `VERIFICATION_FREEZE.json` recording `VERIFICATION_ID`,")
    a("`MANIFEST_SHA256`, `VERIFICATION_FINDINGS_SHA256`, the frozen")
    a("`INITIAL_FINDINGS_SHA256` you verified against, a timestamp and your")
    a("session identity; then `VERIFICATION_ATTESTATION.md` stating what you")
    a("executed but did not inspect.")
    a("")

    a("## 7. STOP conditions")
    a("")
    a("Report and STOP, rather than working around, if:")
    a("")
    a("* `MANIFEST.json` does not match the digest you were given, or any")
    a("  payload row does not match its file;")
    a("* `frozen/INITIAL_FINDINGS.md` does not hash to the value")
    a("  `frozen/FREEZE.json` declares;")
    a("* the launcher or the runtime refuses;")
    a("* `unexpected_denials` or `missing_prescribed_denials` is non-empty;")
    a("* a locus named in section 3 is absent from `tree/`;")
    a("* you need something to adjudicate a closure that is not in this package.")
    a("")
    a("**A STOP is not a NOT_CLOSED and costs nothing.** Reporting a defective")
    a("package is the correct outcome for a defective package.")
    a("")
    a("Finally: if you conclude that a finding is closed only because the")
    a("finding was restated more narrowly than you wrote it, say that. The")
    a("frozen text in `frozen/` is authoritative over section 3, and a")
    a("re-scoped finding is itself a result worth returning.")
    return "\n".join(L) + "\n"
